GET http://localhost:3001
###
GET http://localhost:3001/booking
###
GET http://localhost:3001/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiQ2F0aHkyMUBob3RtYWlsLmNvbSIsImlhdCI6MTcyOTEwNDM1MCwiZXhwIjoxNzI5MTA3OTUwfQ.xxsjQN5h3lrewENnHXBNBqcewN1SWZaROYbsmyNVIps
Content-Type: application/json
###
GET http://localhost:3001/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiQWRyaWFuYTk0QGdtYWlsLmNvbSIsImlhdCI6MTcyOTEwNTExMywiZXhwIjoxNzI5MTA4NzEzfQ.ocg51CKxb0eGrpB2JHuxH7A0AA4md7RcgI8DZVw8iGQ
###
GET http://localhost:3001/customer

###
POST http://localhost:3001/login
content-type: application/json

{
  "email": "Adriana94@gmail.com",
  "password": "employer1234"
}
###
POST http://localhost:3001/room
content-type: application/json

{

}
###
POST http://localhost:3001/booking
content-type: application/json

{

}
###
POST http://localhost:3001/user
content-type: application/json

{

}
